filters:
  - filter_type: file
    file_format: Android
    source_language: en
    source_file: app/src/main/res/values/strings.xml
    translation_files_expression: app/src/main/res/values-<lang>/strings.xml
  - filter_type: file
    file_format: Android
    source_language: en
    source_file: app/src/main/res/values/arrays.xml
    translation_files_expression: app/src/main/res/values-<lang>/arrays.xml
  - filter_type: file
    file_format: Android
    source_language: en
    source_file: app/src/main/res/values/plurals.xml
    translation_files_expression: app/src/main/res/values-<lang>/plurals.xml
  - filter_type: dir
    file_format: TXT
    source_file_extension: txt
    source_language: en
    source_file_dir: fastlane/metadata/android/en/
    translation_files_expression: fastlane/metadata/android/<lang>/
    ignore_dirs:
      - fastlane/metadata/android/en/changelogs/
    ignore_files:
      - fastlane/metadata/android/en/video.txt
