# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  before_all do |lane, options|
    move_files(source: "fastlane/metadata/android/en", destination: "fastlane/metadata/android/en-US")
    move_files(source: "fastlane/metadata/android/ru", destination: "fastlane/metadata/android/ru-RU")
  end

  desc "Update metadata"
  lane :meta do
    upload_to_play_store(
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: false,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy a new version to the Google Play for testing"
  lane :beta do
    gradle(task: "clean")

    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'beta',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean")

    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      sync_image_upload: true
    )
  end

  after_all do |lane, options|
    move_files(source: "fastlane/metadata/android/en-US", destination: "fastlane/metadata/android/en")
    move_files(source: "fastlane/metadata/android/ru-RU", destination: "fastlane/metadata/android/ru")
  end
end
