name: Android CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build --warning-mode all

  test-unit:
    name: Run Unit Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Execute unit tests
      run: ./gradlew test --stacktrace
  
  test-instrumentation:
    name: Run Instrumentation Tests

    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [23, 29]
        target: [default]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Execute instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        script: ./gradlew connectedCheck
